In [3]:
from sklearn.feature_extraction.text import  CountVectorizer
import pandas as pd

In [4]:
corpus = [
    "students watch youtube youtube youtube",
    "youtube watch youtube",
    "students write comments",
    "youtube write comments"
]

# create bag of words model

In [5]:
cv = CountVectorizer()

# learn vocabulary and transfrom documnent

In [6]:
X = cv.fit_transform(corpus)

#show vocabulary

In [7]:
cv.get_feature_names_out()

array(['comments', 'students', 'watch', 'write', 'youtube'], dtype=object)

# show bag of words matrix

In [8]:
X.toarray()

array([[0, 1, 1, 0, 3],
       [0, 0, 1, 0, 2],
       [1, 1, 0, 1, 0],
       [1, 0, 0, 1, 1]])

In [10]:
bow_df = pd.DataFrame(
    X.toarray(),
    columns = cv.get_feature_names_out(),
    index = ['D1', 'D2', 'D3', 'D4']
)

bow_df

    comments  students  watch  write  youtube
D1         0         1      1      0        3
D2         0         0      1      0        2
D3         1         1      0      1        0
D4         1         0      0      1        1

```
এখানে কোন word কয়বার আছে সেই frequency টা দেখাচ্ছে। আমরা যদি চাই ওই word টা শুধু আছে কি নাই, সেটা দেখতে তাহলে শুধু "binary=True" করে দিব
```

In [11]:
cv = CountVectorizer(binary = True)

In [13]:
X = cv.fit_transform(corpus)

In [15]:
bow_df = pd.DataFrame(
    X.toarray(),
    columns = cv.get_feature_names_out(),
    index = ['D1', 'D2', 'D3', 'D4']
)

bow_df

    comments  students  watch  write  youtube
D1         0         1      1      0        1
D2         0         0      1      0        1
D3         1         1      0      1        0
D4         1         0      0      1        1

# n_gram

In [21]:
cv = CountVectorizer(ngram_range=(2, 2)) # ngram_range=(min, max) এত গুলা word এক সাথে নিয়ে bag বানাইতে চাই সেটা। যদি ngram_range=(1, 1) দেই তবে সেটা হল bag of word

In [22]:
X = cv.fit_transform(corpus)

In [23]:
cv.get_feature_names_out()

array(['students watch', 'students write', 'watch youtube',
       'write comments', 'youtube watch', 'youtube write',
       'youtube youtube'], dtype=object)

In [24]:
bow_df = pd.DataFrame(
    X.toarray(),
    columns = cv.get_feature_names_out(),
    index = ["D1","D2","D3","D4"]
)
bow_df

,students watch,students write,watch youtube,write comments,youtube watch,youtube write,youtube youtube
D1,1,0,1,0,0,0,2
D2,0,0,1,0,1,0,0
D3,0,1,0,1,0,0,0
D4,0,0,0,1,0,1,0

In [25]:
cv = CountVectorizer(ngram_range=(1, 3))

In [26]:
X = cv.fit_transform(corpus)

In [27]:
cv.get_feature_names_out()

array(['comments', 'students', 'students watch', 'students watch youtube',
       'students write', 'students write comments', 'watch',
       'watch youtube', 'watch youtube youtube', 'write',
       'write comments', 'youtube', 'youtube watch',
       'youtube watch youtube', 'youtube write', 'youtube write comments',
       'youtube youtube', 'youtube youtube youtube'], dtype=object)

In [28]:
bow_df = pd.DataFrame(
    X.toarray(),
    columns = cv.get_feature_names_out(),
    index = ["D1","D2","D3","D4"]
)
bow_df

,comments,students,students watch,students watch youtube,students write,students write comments,watch,watch youtube,watch youtube youtube,write,write comments,youtube,youtube watch,youtube watch youtube,youtube write,youtube write comments,youtube youtube,youtube youtube youtube
D1,0,1,1,1,0,0,1,1,1,0,0,3,0,0,0,0,2,1
D2,0,0,0,0,0,0,1,1,0,0,0,2,1,1,0,0,0,0
D3,1,1,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,0
D4,1,0,0,0,0,0,0,0,0,1,1,1,0,0,1,1,0,0