In [11]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#sklearn preprocessing

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline


#Regression model

from sklearn.linear_model import LinearRegression,Ridge
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor



from sklearn.ensemble import VotingRegressor, StackingRegressor


#metrices

from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error,accuracy_score, classification_report

import warnings
warnings.filterwarnings("ignore")

In [12]:
df= pd.read_excel('dataset.xlsx')
df

,ClaimID,PatientID,ProviderID,ClaimAmount,ClaimDate,DiagnosisCode,ProcedureCode,PatientAge,PatientGender,ProviderSpecialty,ClaimStatus,PatientIncome,PatientMaritalStatus,PatientEmploymentStatus,ProviderLocation,ClaimType,ClaimSubmissionMethod,Cluster,ClaimLegitimacy
0,4d76c7f7-d36a-4139-b451-a9a4ad10d7d5,19cf2638-3ec0-4ed9-9995-d9ba4553813a,a3d0cc80-dffe-40ff-a302-23c8ffeedb36,7820.52,2024-07-08,Ta150,iO013,96,F,Orthopedics,Pending,57595.11,Single,Employed,New Alishaview,Inpatient,Paper,3,Legitimate
1,e35193b4-3609-492b-866a-98de19317e9c,5c4bb6c5-4dd3-4a86-85fa-f36c0d8debff,a9f25acf-92b8-45e2-9cef-87bd07d0a591,5453.86,2024-07-08,Fo766,jR349,95,M,Cardiology,Denied,140772.72,Widowed,Employed,East Curtis,Inpatient,Online,2,Legitimate
2,1f3fa373-25ed-4ff4-b6c7-38dcb2fb297f,777866e0-4d10-45a8-a7b4-dbdaa26d5a81,951b1e08-9948-4956-80e5-9277f16bd290,8229.86,2024-07-08,AX876,uU479,10,M,Cardiology,Pending,69803.19,Married,Student,Lake Jennifer,Emergency,Online,3,Legitimate
3,af6a68f4-8319-47b1-a28b-77de01572851,9d7c53ee-eb1a-4f07-9e3a-e86cf82e9f0f,de9e193a-f9a1-4d63-9345-aefe75694628,9519.16,2024-07-08,SQ441,Xs264,59,F,Cardiology,Pending,135530.12,Married,Employed,Martinstad,Routine,Phone,2,Legitimate
4,417fe944-79d2-4610-81c4-a2d496f29ee4,db14b0ca-ac2a-4e83-b085-947ea32e7587,5c7d7045-71b6-4c15-937c-43e4cfe65bf4,3226.15,2024-07-08,FK970,PV476,36,F,Neurology,Approved,36995.52,Divorced,Unemployed,Thomasfurt,Inpatient,Phone,1,Legitimate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,6c427360-20ae-43b8-802f-bd25fae3ce09,c0ddd919-1b16-4689-9963-7566ba410835,c0039b67-ace3-4f97-a646-4214419f9fdf,3041.50,2022-07-09,qJ110,bn806,10,M,General Practice,Denied,80395.76,Widowed,Student,New Melissastad,Emergency,Paper,3,Legitimate
4496,43b72c25-94ae-4f1f-a2fb-cb3297978674,02ea4377-cf98-4251-a1d6-8eb720d903d8,2dcbfa56-e73a-42b5-bfbf-02bfb9b3f990,5153.28,2022-07-09,dc670,wX329,96,F,Neurology,Pending,31560.84,Widowed,Retired,Lake Cathymouth,Outpatient,Phone,1,Legitimate
4497,e0bf8e55-7440-48bb-9583-187ab12a5682,14844cfb-2bff-4be5-8540-7d58c72ed309,ae3fdf78-c574-495a-ba8a-2246ba1d61a5,6908.45,2022-07-09,cF152,aT402,97,F,Pediatrics,Denied,74973.94,Married,Unemployed,Garyborough,Inpatient,Online,3,Legitimate
4498,1a3f947a-f3a7-4286-8925-aed2eced6ee2,cfedbf0b-43eb-4dbe-a26b-74bd566898c8,d344683d-f2e2-4262-8c04-f9e92fda1d33,5830.19,2022-07-09,Sc398,wv342,14,F,General Practice,Approved,147665.80,Widowed,Student,East Claudiafurt,Routine,Paper,2,Legitimate
4499,291cfa64-9956-40e7-b89f-4628650f42f0,2bd2d173-4ce1-428d-836c-259d9236a839,cf84cf99-0ac3-465a-af90-239a873bafa5,5848.92,2022-07-09,TQ972,Sn273,47,M,Pediatrics,Approved,131676.02,Married,Unemployed,North Amberborough,Inpatient,Phone,2,Legitimate

# Y Data Profiling

In [13]:
# ! pip install ydata-profiling

In [14]:
# from ydata_profiling import ProfileReport

# profile = ProfileReport( df , title="Bangladesh Student performance prediction", explorative = True  )

# profile.to_file("ydata.html")

In [15]:
df.shape

(4500, 19)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ClaimID                  4500 non-null   str
 1   PatientID                4500 non-null   str
 2   ProviderID               4500 non-null   str
 3   ClaimAmount              4500 non-null   float64
 4   ClaimDate                4500 non-null   datetime64[us]
 5   DiagnosisCode            4500 non-null   str
 6   ProcedureCode            4500 non-null   str
 7   PatientAge               4500 non-null   int64
 8   PatientGender            4500 non-null   str
 9   ProviderSpecialty        4500 non-null   str
 10  ClaimStatus              4500 non-null   str
 11  PatientIncome            4500 non-null   float64
 12  PatientMaritalStatus     4500 non-null   str
 13  PatientEmploymentStatus  4500 non-null   str
 14  ProviderLocation         4500 non-null   str
 15  ClaimType                4500 non-null   str
 16  ClaimSubmissionMethod    4500 non-null   str
 17  Cluster                  4500 non-null   int64
 18  ClaimLegitimacy          4500 non-null   str
dtypes: datetime64[us](1), float64(2), int64(2), str(14)
memory usage: 668.1 KB

In [17]:
df.describe()

,ClaimAmount,ClaimDate,PatientAge,PatientIncome,Cluster
count,4500.000000,4500,4500.000000,4500.000000,4500.000000
mean,5014.203867,2023-07-05 06:48:38.400000,49.838444,84384.284084,1.503111
min,100.120000,2022-07-09 00:00:00,0.000000,20006.870000,0.000000
25%,2509.072500,2023-01-07 18:00:00,25.000000,52791.905000,0.000000
50%,5053.765000,2023-07-03 00:00:00,50.500000,84061.205000,2.000000
75%,7462.452500,2023-12-29 00:00:00,75.000000,115768.417500,3.000000
max,9997.200000,2024-07-08 00:00:00,99.000000,149957.520000,3.000000
std,2866.291066,NaN,28.790471,37085.908878,1.127261

In [18]:
df.isna().sum()

ClaimID                    0
PatientID                  0
ProviderID                 0
ClaimAmount                0
ClaimDate                  0
DiagnosisCode              0
ProcedureCode              0
PatientAge                 0
PatientGender              0
ProviderSpecialty          0
ClaimStatus                0
PatientIncome              0
PatientMaritalStatus       0
PatientEmploymentStatus    0
ProviderLocation           0
ClaimType                  0
ClaimSubmissionMethod      0
Cluster                    0
ClaimLegitimacy            0
dtype: int64

In [19]:
df.isnull().sum()

ClaimID                    0
PatientID                  0
ProviderID                 0
ClaimAmount                0
ClaimDate                  0
DiagnosisCode              0
ProcedureCode              0
PatientAge                 0
PatientGender              0
ProviderSpecialty          0
ClaimStatus                0
PatientIncome              0
PatientMaritalStatus       0
PatientEmploymentStatus    0
ProviderLocation           0
ClaimType                  0
ClaimSubmissionMethod      0
Cluster                    0
ClaimLegitimacy            0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.drop_duplicates(inplace=True)

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df.shape

(4500, 19)

In [25]:
corr_target= df.select_dtypes(include=np.number).corr()['ClaimLegitimacy'].sort_values(ascending=False)
print(corr_target)

KeyError: 'ClaimLegitimacy'

In [ ]:
X= df.drop('Diabetes_012', axis=1)
y=df['Diabetes_012']

In [ ]:
preprocessor= Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler',StandardScaler())
    ]
)

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Ensemble - Boosting, Stacking

In [ ]:
reg_lr= LinearRegression()
reg_rf= RandomForestRegressor(n_estimators=100, random_state=42)
reg_gb=GradientBoostingRegressor(n_estimators=100, random_state=42)

In [ ]:
#  voting regressor
voting_reg= VotingRegressor(
    estimators=[
        ('lr', reg_lr),
        ('rf', reg_rf),
        ('gb', reg_gb)
    ]
)

In [ ]:
# stacking
stacking_reg= StackingRegressor(
    estimators=[
        ('rf', reg_rf),
        ('gb', reg_gb)
    ],
    final_estimator= Ridge() # meta lerner
)

In [ ]:
# dictonary of all model

model_to_train= {
    'Liner Regression': reg_lr,
    'Random Forest': reg_rf,
    'Gradient Boosting': reg_gb,
    'Voting Ensemble': voting_reg,
    'Stacking Ensemble': stacking_reg
}

In [ ]:
# training
result=[]

for name, model in model_to_train.items():
    pipe= Pipeline([
        ('preprocessor', preprocessor),
        ('model', model)
    ])
    
    pipe.fit(X_train, y_train)
    y_pred= pipe.predict(X_test)
    
    r2= r2_score(y_test, y_pred)
    rmse=np.sqrt(mean_squared_error(y_test, y_pred))
    mae=mean_absolute_error(y_test, y_pred)
    
    result.append({
        'Model': name,
        'R2 Score': r2,
        'RMSE': rmse,
        'MAE': mae
    })
    
result_df=pd.DataFrame(result).sort_values('R2 Score', ascending=False)
print(result_df)

In [ ]:
best_model_name = result_df.iloc[0]['Model']
best_model_obj = model_to_train[best_model_name]


#fit the best model

final_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model',best_model_obj)
])

final_pipe.fit(X_train,y_train)
y_final_pred = final_pipe.predict(X_test)


#plot Actual vs predicted

plt.figure( figsize = (8,6) )

sns.scatterplot(x=y_test, y=y_final_pred, alpha = 0.6, color='teal' )
plt.plot( [2,5] , [2,5], color = "red", linestyle = '--'  )

plt.xlabel("Actual HSC Result")
plt.ylabel("Predicted HSC result")

plt.grid(True)
plt.show()