In [1]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use("fivethirtyeight")

In [2]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self, inputs, weights):
    z = np.dot(inputs, weights)
    return np.where(z > 0 , 1, 0)

  def fit(self, X, y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))] # concactination
    print(f"X_with_bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch: {epoch}")
      y_hat = self.activationFunction(X_with_bias, self.weights)
      print(f"predicted value: \n{y_hat}")
      error = self.y - y_hat
      print(f"error: \n{error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
      print(f"updated weights: \n{self.weights}")
      print("#############\n")

  def predict(self, X):
    X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
    return self.activationFunction(X_with_bias, self.weights)

In [3]:
data= {'x1': [0, 0, 1, 1], 'X2':[0, 1, 0, 1], 'y':[0, 0, 0, 1]}

AND= pd.DataFrame(data)
AND

   x1  X2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [4]:
X= AND.drop('y', axis=1)
X

   x1  X2
0   0   0
1   0   1
2   1   0
3   1   1

In [5]:
y= AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [6]:
model= Perceptron(eta=0.5, epochs=10)
model.fit(X, y)

self.weights: [-5.73663744e-05 -5.07661900e-05  1.02674919e-04]
X_with_bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch: 0
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[ 0.49994263  0.49994923 -0.49989733]
#############

for epoch: 1
predicted value:
[1 1 1 1]
error:
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights:
[-5.73663744e-05 -5.07661900e-05  1.00010267e+00]
#############

for epoch: 2
predicted value:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:
[0.49994263 0.49994923 0.50010267]
#############

for epoch: 3
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49994263 0.49994923 0.50010267]
#############

for epoch: 4
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49994263 0.49994923 0.50010267]
#############

for epoch: 5
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49994263 0.49994923 0.50010267]
#############

for epoch: 6
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49994263 0.49994923 0.50010267]
#############

for epoch: 7
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49994263 0.49994923 0.50010267]
#############

for epoch: 8
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49994263 0.49994923 0.50010267]
#############

for epoch: 9
predicted value:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:
[0.49994263 0.49994923 0.50010267]
#############

In [7]:
model.predict(X)

array([0, 0, 0, 1])

In [8]:
model.weights

array([0.49994263, 0.49994923, 0.50010267])