In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IMDB Dataset.csv')
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
df.shape

(50000, 2)

In [4]:
df.columns

Index(['review', 'sentiment'], dtype='str')

# Basic Preprocessing

## Make it Lowercase

In [5]:
df['review'] = df['review'].str.lower()

In [6]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: str

In [7]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

## Remove HTML Tags

In [8]:
import re

def remove_html_tags(text): # আমরা regular experation এর জন্য function দিয়ে কাজ করব, তাহলে সুবিধা হবে
    pattern = re.compile(r'<.*?>')
    return pattern.sub(r'', text)

In [9]:
remove_html_tags(df['review'][3])

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [10]:
df['review'] = df['review'].apply(remove_html_tags)

In [11]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: str

## Remove URL

```
এটা আমাদের dataset এ নাই, তাই আলাদা ভাবে দিচ্ছি
```

In [12]:
text1= '''
Yesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.

For research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.

If you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.

'''

In [13]:
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.\n\nFor research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.\n\nIf you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.\n\n"

In [14]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [15]:
remove_url(text1)

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on  and also watched tutorials at \n\nFor research papers, I visited  and read documentation from  One of my friends also shared a blog post available at \n\nIf you'd like to practice coding problems, check out  or  These websites are very helpful for aspiring AI engineers.\n\n"

## Remove punctuations

In [16]:
import string

In [17]:
exclude = string.punctuation

In [18]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

### way 1, slow

In [19]:
def remove_punc1(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

In [20]:
remove_punc1('Hi, I am Sultan.Mahamud.Opu?!')

'Hi I am SultanMahamudOpu'

### way 2, fast

In [21]:
def remove_punc(text):
    return text.translate(str.maketrans(' ', ' ', exclude))

In [22]:
remove_punc('Hi, I am Sultan.Mahamud.Opu?!')

'Hi I am SultanMahamudOpu'

In [23]:
df['review'] = df['review'].apply(remove_punc)

In [24]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Chat words treatment
## short form কে long for এ আনা

In [25]:
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired",
    "OMG!": "Oh My God",
    "SMH": "Shaking My Head",
    "NGL": "Not Gonna Lie",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "IMO": "In My Opinion",
    "IMHO": "In My Honest Opinion",
    "RN": "Right Now",
    "FR": "For Real",
    "DW": "Don't Worry",
    "ILYSM": "I Love You So Much",
    "OMW": "On My Way",
    "GGWP": "Good Game Well Played",
    "GG": "Good Game",
    "EZ": "Easy",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud"
}

In [26]:
def chat_conversion(text):
    new_text = []
    
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
            
    return ' '.join(new_text)

In [27]:
chat_conversion('afk omg! ok')

'Away From Keyboard Oh My God ok'

In [28]:
df['review'] = df['review'].apply(chat_conversion)

In [29]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend Te...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the Tears In My Eyes of...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

# Spell checking

In [30]:
! pip install textblob

Requirement already satisfied: textblob in C:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (0.20.1)
Requirement already satisfied: nltk>=3.9 in C:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from textblob) (3.10.3)
Requirement already satisfied: defusedxml in C:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from nltk>=3.9->textblob) (0.7.1)
Requirement already satisfied: click in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (8.4.2)
Requirement already satisfied: joblib in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from nltk>=3.9->textblob) (2026.9.3)
Requirement already satisfied: tqdm in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from nltk>=3.9->textblob) (4.67.3)
Requirement already satisfied: colorama in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

In [31]:
from textblob import TextBlob

In [32]:
incorrect_text = 'Helllo this is Sultan'

In [33]:
textblb = TextBlob(incorrect_text)
textblb.correct().string

'Hello this is Sultan'

# Stopwords removal

In [34]:
text = """
Yesterday, I was working on a Machine Learning project in PHITRON, and I was trying to understand how the model is performing on the dataset. The dataset is quite large, and it contains a lot of reviews that are written by users from different countries.

I noticed that the model is not performing well for some of the samples, especially those that are very short or have too many stopwords in them. Because of this, I decided to clean the text data and remove unnecessary words that do not contribute much to the meaning of the sentence.

While I was doing this, I also checked how the preprocessing steps like tokenization, lowercasing, and punctuation removal are affecting the dataset. It was interesting to see that after removing stopwords, the text becomes more meaningful and easier for the model to understand.

In addition to that, I was also reading some documentation from https://scikit-learn.org/stable/ and watching tutorials on https://www.youtube.com while comparing different NLP techniques. The goal is to improve the accuracy of the model and make it more robust for real-world applications.

Overall, I think that removing stopwords is an important step in the NLP pipeline because it helps reduce noise and improve performance of machine learning models.
"""

In [35]:
import nltk
from nltk.corpus import stopwords

In [36]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\skmah\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [37]:
stop_words = set(stopwords.words('bengali')) # fast access এর জন্য set use করছি

In [38]:
stop_words

{'অতএব',
 'অথচ',
 'অথবা',
 'অনুযায়ী',
 'অনেক',
 'অনেকে',
 'অনেকেই',
 'অন্তত',
 'অন্য',
 'অবধি',
 'অবশ্য',
 'অর্থাত',
 'আই',
 'আগামী',
 'আগে',
 'আগেই',
 'আছে',
 'আজ',
 'আদ্যভাগে',
 'আপনার',
 'আপনি',
 'আবার',
 'আমরা',
 'আমাকে',
 'আমাদের',
 'আমার',
 'আমি',
 'আর',
 'আরও',
 'ই',
 'ইত্যাদি',
 'ইহা',
 'উচিত',
 'উত্তর',
 'উনি',
 'উপর',
 'উপরে',
 'এ',
 'এঁদের',
 'এঁরা',
 'এই',
 'একই',
 'একটি',
 'একবার',
 'একে',
 'এক্',
 'এখন',
 'এখনও',
 'এখানে',
 'এখানেই',
 'এটা',
 'এটাই',
 'এটি',
 'এত',
 'এতটাই',
 'এতে',
 'এদের',
 'এব',
 'এবং',
 'এবার',
 'এমন',
 'এমনকী',
 'এমনি',
 'এর',
 'এরা',
 'এল',
 'এস',
 'এসে',
 'ঐ',
 'ও',
 'ওঁদের',
 'ওঁর',
 'ওঁরা',
 'ওই',
 'ওকে',
 'ওখানে',
 'ওদের',
 'ওর',
 'ওরা',
 'কখনও',
 'কত',
 'কবে',
 'কমনে',
 'কয়েক',
 'কয়েকটি',
 'করছে',
 'করছেন',
 'করতে',
 'করবে',
 'করবেন',
 'করলে',
 'করলেন',
 'করা',
 'করাই',
 'করায়',
 'করার',
 'করি',
 'করিতে',
 'করিয়া',
 'করিয়ে',
 'করে',
 'করেই',
 'করেছিলেন',
 'করেছে',
 'করেছেন',
 'করেন',
 'কাউকে',
 'কাছ',
 'কাছে',
 'কাজ',
 'কাজে',
 'কারও',
 'কারণ',
 'কি',
 'কিংবা',
 'কিছু',
 'কিছুই',
 'কিন্তু',
 'কী',
 'কে',
 'কেউ',
 'কেউই',
 'কেখা',
 'কেন',
 'কোটি',
 'কোন',
 'কোনও',
 'কোনো',
 'ক্ষেত্রে',
 'কয়েক',
 'খুব',
 'গিয়ে',
 'গিয়েছে',
 'গিয়ে',
 'গুলি',
 'গেছে',
 'গেল',
 'গেলে',
 'গোটা',
 'চলে',
 'চান',
 'চায়',
 'চার',
 'চালু',
 'চেয়ে',
 'চেষ্টা',
 'ছাড়া',
 'ছাড়াও',
 'ছিল',
 'ছিলেন',
 'জন',
 'জনকে',
 'জনের',
 'জন্য',
 'জন্যওজে',
 'জানতে',
 'জানা',
 'জানানো',
 'জানায়',
 'জানিয়ে',
 'জানিয়েছে',
 'জে',
 'জ্নজন',
 'টি',
 'ঠিক',
 'তখন',
 'তত',
 'তথা',
 'তবু',
 'তবে',
 'তা',
 'তাঁকে',
 'তাঁদের',
 'তাঁর',
 'তাঁরা',
 'তাঁাহারা',
 'তাই',
 'তাও',
 'তাকে',
 'তাতে',
 'তাদের',
 'তার',
 'তারপর',
 'তারা',
 'তারৈ',
 'তাহলে',
 'তাহা',
 'তাহাতে',
 'তাহার',
 'তিনঐ',
 'তিনি',
 'তিনিও',
 'তুমি',
 'তুলে',
 'তেমন',
 'তো',
 'তোমার',
 'থাকবে',
 'থাকবেন',
 'থাকা',
 'থাকায়',
 'থাকে',
 'থাকেন',
 'থেকে',
 'থেকেই',
 'থেকেও',
 'দিকে',
 'দিতে',
 'দিন',
 'দিয়ে',
 'দিয়েছে',
 'দিয়েছেন',
 'দিলেন',
 'দু',
 'দুই',
 'দুটি',
 'দুটো',
 'দেওয়া',
 'দেওয়ার',
 'দেওয়া',
 'দেখতে',
 'দেখা',
 'দেখে',
 'দেন',
 'দেয়',
 'দ্বারা',
 'ধরা',
 'ধরে',
 'ধামার',
 'নতুন',
 'নয়',
 'না',
 'নাই',
 'নাকি',
 'নাগাদ',
 'নানা',
 'নিজে',
 'নিজেই',
 'নিজেদের',
 'নিজের',
 'নিতে',
 'নিয়ে',
 'নিয়ে',
 'নেই',
 'নেওয়া',
 'নেওয়ার',
 'নেওয়া',
 'নয়',
 'পক্ষে',
 'পর',
 'পরে',
 'পরেই',
 'পরেও',
 'পর্যন্ত',
 'পাওয়া',
 'পাচ',
 'পারি',
 'পারে',
 'পারেন',
 'পি',
 'পেয়ে',
 'পেয়্র্',
 'প্রতি',
 'প্রথম',
 'প্রভৃতি',
 'প্রযন্ত',
 'প্রাথমিক',
 'প্রায়',
 'প্রায়',
 'ফলে',
 'ফিরে',
 'ফের',
 'বক্তব্য',
 'বদলে',
 'বন',
 'বরং',
 'বলতে',
 'বলল',
 'বললেন',
 'বলা',
 'বলে',
 'বলেছেন',
 'বলেন',
 'বসে',
 'বহু',
 'বা',
 'বাদে',
 'বার',
 'বি',
 'বিনা',
 'বিভিন্ন',
 'বিশেষ',
 'বিষয়টি',
 'বেশ',
 'বেশি',
 'ব্যবহার',
 'ব্যাপারে',
 'ভাবে',
 'ভাবেই',
 'মতো',
 'মতোই',
 'মধ্যভাগে',
 'মধ্যে',
 'মধ্যেই',
 'মধ্যেও',
 'মনে',
 'মাত্র',
 'মাধ্যমে',
 'মোট',
 'মোটেই',
 'যখন',
 'যত',
 'যতটা',
 'যথেষ্ট',
 'যদি',
 'যদিও',
 'যা',
 'যাঁর',
 'যাঁরা',
 'যাওয়া',
 'যাওয়ার',
 'যাওয়া',
 'যাকে',
 'যাচ্ছে',
 'যাতে',
 'যাদের',
 'যান',
 'যাবে',
 'যায়',
 'যার',
 'যারা',
 'যিনি',
 'যে',
 'যেখানে',
 'যেতে',
 'যেন',
 'যেমন',
 'র',
 'রকম',
 'রয়েছে',
 'রাখা',
 'রেখে',
 'লক্ষ',
 'শুধু',
 'শুরু',
 'সঙ্গে',
 'সঙ্গেও',
 'সব',
 'সবার',
 'সমস্ত',
 'সম্প্রতি',
 'সহ',
 'সহিত',
 'সাধারণ',
 'সামনে',
 'সি',
 'সুতরাং',
 'সে',
 'সেই',
 'সেখান',
 'সেখানে',
 'সেটা',
 'সেটাই',
 'সেটাও',
 'সেটি',
 'স্পষ্ট',
 'স্বয়ং',
 'হইতে',
 'হইবে',
 'হইয়া',
 'হওয়া',
 'হওয়ায়',
 'হওয়ার',
 'হচ্ছে',
 'হত',
 'হতে',
 'হতেই',
 'হন',
 'হবে',
 'হবেন',
 'হয়',
 'হয়তো',
 'হয়নি',
 'হয়ে',
 'হয়েই',
 'হয়েছিল',
 'হয়েছে',
 'হয়েছেন',
 'হল',
 'হলে',
 'হলেই',
 'হলেও',
 'হলো',
 'হাজার',
 'হিসাবে',
 'হৈলে',
 'হোক',
 'হয়'}

In [39]:
stop_words = set(stopwords.words('english'))

In [40]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [41]:
def remove_stopwords(text):
    words = text.split()
    cleaned = []
    
    for word in words:
        word = word.lower().strip(string.punctuation)
        
        if word and word not in stop_words:
            cleaned.append(word)
    
    return ' '.join(cleaned)

In [42]:
remove_stopwords(text)

'yesterday working machine learning project phitron trying understand model performing dataset dataset quite large contains lot reviews written users different countries noticed model performing well samples especially short many stopwords decided clean text data remove unnecessary words contribute much meaning sentence also checked preprocessing steps like tokenization lowercasing punctuation removal affecting dataset interesting see removing stopwords text becomes meaningful easier model understand addition also reading documentation https://scikit-learn.org/stable watching tutorials https://www.youtube.com comparing different nlp techniques goal improve accuracy model make robust real-world applications overall think removing stopwords important step nlp pipeline helps reduce noise improve performance machine learning models'

In [43]:
df['review'] = df['review'].apply(remove_stopwords)
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend tears eyes hot sum...
3        basically theres family little boy jake thinks...
4        petter matteis love tears eyes money visually ...
                               ...
49995    thought movie right good job wasnt creative or...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    im going disagree previous comment side maltin...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: str

# Emoji removal

In [44]:
text_with_emoji = '''Yesterday I completed my Machine Learning project on sentiment analysis 😊🔥.
The model performed really well on the IMDB dataset 👍🎯.
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming 📚💡.
However, debugging errors was quite frustrating 😓💻.
Overall, the experience was amazing and I feel more confident now 🚀😄.'''

In [45]:
import re

def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags
        "\U00002700-\U000027BF"  # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub(r'', text)

In [46]:
clean_text = remove_emoji(text_with_emoji)
print(clean_text)

Yesterday I completed my Machine Learning project on sentiment analysis .
The model performed really well on the IMDB dataset .
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming .
However, debugging errors was quite frustrating .
Overall, the experience was amazing and I feel more confident now .

In [47]:
df['review'] = df['review'].apply(remove_emoji)
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend tears eyes hot sum...
3        basically theres family little boy jake thinks...
4        petter matteis love tears eyes money visually ...
                               ...
49995    thought movie right good job wasnt creative or...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    im going disagree previous comment side maltin...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: str

# Tokenization
```
tokenization করি যাতে একই word একাধিক বার ব্যবহার না হয়। একটা word যেন একবারই use হয়। তাই সব word কে আলাদা করে ফেলি
```
## NLTK

In [48]:
from nltk.tokenize import word_tokenize,sent_tokenize
import nltk

In [49]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\skmah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\skmah\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [50]:
# word tokenize
sent1 = 'I am going to visit Dhaka!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'Dhaka', '!']

In [51]:
# sentence tokenize
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [52]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

# Spacy

In [53]:
import sys
!{sys.executable} -m pip install spacy

Requirement already satisfied: spacy in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (3.8.16)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (0.27.0)
Requirement already satisfied: click<9.0.0,>=8.2.1 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (8.4.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (2.4.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (2.34.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (70.2.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from spacy) (26.2)
Requirement already satisfied: colorama in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from click<9.0.0,>=8.2.1->spacy) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.5.20)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.25.0)
Requirement already satisfied: smart-open>=5.2.1 in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.1)
Requirement already satisfied: httpx>=0.24.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in c:\Users\skmah\.conda\envs\gpu_env\Lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.4.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\skmah\AppData\Roaming\Python\Python314\site-packages (from jinja2->spacy) (3.0.3)

In [55]:
import sys
!{sys.executable} -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     ----- ---------------------------------- 1.8/12.8 MB 6.8 MB/s eta 0:00:02
     ---------- ----------------------------- 3.4/12.8 MB 7.2 MB/s eta 0:00:02
     --------------- ------------------------ 5.0/12.8 MB 7.6 MB/s eta 0:00:02
     -------------------- ------------------- 6.6/12.8 MB 7.3 MB/s eta 0:00:01
     ----------------------- ---------------- 7.6/12.8 MB 6.9 MB/s eta 0:00:01
     -------------------------- ------------- 8.4/12.8 MB 6.5 MB/s eta 0:00:01
     ----------------------------- ---------- 9.4/12.8 MB 6.3 MB/s eta 0:00:01
     --------------------------------- ------ 10.7/12.8 MB 6.4 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 6.5 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 6.5 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 6.5 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 5.2 MB/s  0:00:02
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [56]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [57]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [58]:
for token in doc2:
    print(token)

We
're
here
to
help
!
mail
us
at
nks@gmail.com

# Stemming

In [59]:
from nltk.stem.porter import PorterStemmer

In [60]:
ps = PorterStemmer()

def stem_words(text):
    return ' '.join([ps.stem(word) for word in text.split()])

In [61]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

# Lemmatization

```
stemming এমনি কোন word ছোট করে দেয়। সেটা dictionary word কি না, সেটা দেখে না।
lemmatization কোন word এর correct dictionary base form এ নিয়ে আসে।
lematization অবশ্যই ভালো, তবে এটায় time বেশি লাগে
```

In [62]:
import  nltk
from nltk.stem import WordNetLemmatizer

In [63]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\skmah\AppData\Roaming\nltk_data...

True

In [64]:
wordnet_nemmatizer = WordNetLemmatizer()

In [76]:
sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."

In [77]:
sentence = remove_punc(sentence)

In [78]:
sentence = sentence.split()
sentence

['He',
 'was',
 'running',
 'and',
 'eating',
 'at',
 'same',
 'time',
 'He',
 'has',
 'bad',
 'habit',
 'of',
 'swimming',
 'after',
 'playing',
 'long',
 'hours',
 'in',
 'the',
 'Sun']

In [81]:
print("{0:20}{1:20}".format("Word","Lemma")) # {0:20}{1:20} এগুলা টেবিলের মত format দেখানোর জন্য আর কিছুই না

for word in sentence:
    print('{0:20}{1:20}'.format(word, wordnet_nemmatizer.lemmatize(word, pos='v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun